[package]
name = "goupil-util"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "~0.12", features = ["blocking", "json"]}
tiny_http = "0.12"
log = "0.4"
chrono = {version = "0.4", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
